# CodeRabbit configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: ja-JP

reviews:
  # レビューの詳細度
  profile: chill

  # AIエージェント向けプロンプトをコメントとして自動投稿
  # これにより、"Prompt for AI Agents" の内容が@claudeメンションとして投稿されます
  auto_review:
    enabled: true
    # AIエージェントプロンプトを投稿
    drafts: false

  # コメント設定
  collapse_walkthrough: false

  # レビューコメントのフォーマット
  request_changes_workflow: true

# AIエージェント統合設定
# CodeRabbitの "Prompt for AI Agents" を自動的にコメントとして投稿
chat:
  # AIエージェント向けのプロンプトを含める
  auto_reply: true

# @claudeメンションを含むコメントテンプレート
# CodeRabbitが重大な問題を検出した時に、自動的に@claudeをメンション
knowledge_base:
  # カスタムルール: Criticalな問題には@claudeをタグ付け
  learnings:
    - pattern: "Critical"
      action: "mention"
      mention: "@claude"
